#define MAX_NO_MODEL_INSTANCES 10
#define MAX_NO_MODEL2D_INSTANCES 10

#define MAX_NO_TEXTURE_UNITS 32
#define MAX_NO_TEXTURE_UNITS_M MAX_NO_TEXTURE_UNITS
#define NULL_TEXTURE_IDX 255

#define MAX_POINT_LIGHTS 1
#define MAX_SPOT_LIGHTS 1

typedef uint16_t inst_flag_type;